export const SET_REVIEW = "VSF_YOTPO/SET_REVIEW";
export const SET_PRODUCT_REVIEWS = "VSF_YOTPO/SET_PRODUCT_REVIEWS";
export const SET_PRODUCT_BOTTOMLINE = "VSF_YOTPO/SET_PRODUCT_BOTTOMLINE";
export const SET_USER_REVIEWS = "VSF_YOTPO/SET_USER_REVIEWS";
export const SET_WIDGET_SITE_REVIEWS = "VSF_YOTPO/SET_WIDGET_SITE_REVIEWS";
export const SET_ALBUM_PHOTOS = "VSF_YOTPO/SET_ALBUM_PHOTOS";
export const VOTE_UP_REVIEW = "VSF_YOTPO/VOTE_UP_REVIEW";
export const VOTE_DOWN_REVIEW = "VSF_YOTPO/VOTE_DOWN_REVIEW";
